version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip3 install -r requirements.txt
artifacts:
  files:
    - app.py
    - requirements.txt
    - appspec.yml
    - scripts/start_server.sh
    